export const codesNonBindable = new Set(["Escape", "MetaLeft", "MetaRight"]);

export const cigInputNonBinable = new Set(["escape", "win", "fn", "print"]);

export const keyCodeToCigInput: Record<string, string> = {
  Escape: "escape",
  MetaLeft: "win",
  MetaRight: "win",
  ControlLeft: "lctrl",
  ControlRight: "rctrl",
  AltLeft: "lalt",
  AltRight: "ralt",
  ShiftLeft: "lshift",
  ShiftRight: "rshift",

  Digit1: "1",
  Digit2: "2",
  Digit3: "3",
  Digit4: "4",
  Digit5: "5",
  Digit6: "6",
  Digit7: "7",
  Digit8: "8",
  Digit9: "9",
  Digit0: "0",

  KeyA: "a",
  KeyB: "b",
  KeyC: "c",
  KeyD: "d",
  KeyE: "e",
  KeyF: "f",
  KeyG: "g",
  KeyH: "h",
  KeyI: "i",
  KeyJ: "j",
  KeyK: "k",
  KeyL: "l",
  KeyM: "m",
  KeyN: "n",
  KeyO: "o",
  KeyP: "p",
  KeyQ: "q",
  KeyR: "r",
  KeyS: "s",
  KeyT: "t",
  KeyU: "u",
  KeyV: "v",
  KeyW: "w",
  KeyX: "x",
  KeyY: "y",
  KeyZ: "z",

  F1: "f1",
  F2: "f2",
  F3: "f3",
  F4: "f4",
  F5: "f5",
  F6: "f6",
  F7: "f7",
  F8: "f8",
  F9: "f9",
  F10: "f10",
  F11: "f11",
  F12: "f12",

  Backquote: "backtick",
  Minus: "minues",
  Equal: "equal",
  Backspace: "backspace",
  Tab: "tab",
  BracketLeft: "lbracket",
  BracketRight: "rbracket",
  Backslash: "backslash",
  CapsLock: "capslock",
  Semicolon: "semicolon",
  Quote: "apostrophe",
  Enter: "enter",
  Comma: "comma",
  Period: "period",
  Slash: "slash",

  Delete: "delete",
  Home: "home",
  End: "end",
  PageUp: "pgup",
  PageDown: "pgdn",

  ArrowUp: "up",
  ArrowDown: "down",
  ArrowLeft: "left",
  ArrowRight: "right",

  NumLock: "numlock",
  NumpadDivide: "np_divide",
  NumpadMultiply: "np_multiply",
  NumpadSubtract: "np_subtract",
  NumpadAdd: "np_add",
  NumpadEnter: "np_enter",
  NumpadDecimal: "np_period",

  Numpad0: "np_0",
  Numpad1: "np_1",
  Numpad2: "np_2",
  Numpad3: "np_3",
  Numpad4: "np_4",
  Numpad5: "np_5",
  Numpad6: "np_6",
  Numpad7: "np_7",
  Numpad8: "np_8",
  Numpad9: "np_9",
};
