export const codesNonBindable = new Set(["Escape", "MetaLeft", "MetaRight"]);

export const cigInputNonBinable = new Set(["escape", "win", "fn", "print"]);

export const keyCodeLabels: Record<string, string> = {
  escape: "Esc",
  backtick: "`",
  minus: "-",
  minues: "-",
  equals: "=",
  equal: "=",
  backspace: "Backspace",
  tab: "Tab",
  lbracket: "[",
  rbracket: "]",
  backslash: "\\",
  capslock: "Caps",
  semicolon: ";",
  apostrophe: "'",
  enter: "Enter",
  comma: ",",
  period: ".",
  slash: "/",
  lshift: "L Shift",
  rshift: "R Shift",
  lctrl: "L Ctrl",
  rctrl: "R Ctrl",
  lalt: "L Alt",
  ralt: "R Alt",
  win: "Win",
  space: "Space",
  fn: "Fn",
  menu: "Menu",
  print: "PrtSc",
  scrolllock: "Scroll",
  pause: "Pause",
  insert: "Ins",
  delete: "Del",
  home: "Home",
  end: "End",
  pgup: "PgUp",
  pgdn: "PgDn",
  up: "Up",
  down: "Down",
  left: "Left",
  right: "Right",
  numlock: "Num",
  np_divide: "/",
  np_multiply: "*",
  np_subtract: "-",
  np_add: "+",
  np_enter: "Enter",
  np_period: ".",
  mouse1: "Mouse 1",
  mouse2: "Mouse 2",
  mouse3: "Mouse 3",
  mwheel_up: "Wheel Up",
  mwheel_down: "Wheel Down",
};

for (let i = 0; i <= 9; i += 1) {
  keyCodeLabels[`np_${i}`] = `${i}`;
}

export function formatKeyLabel(code: string): string {
  if (!code) return "";
  if (keyCodeLabels[code]) return keyCodeLabels[code];
  if (code.length === 1) return code.toUpperCase();
  if (/^f\d+$/i.test(code)) return code.toUpperCase();
  return code;
}

export const keyCodeToCigInput: Record<string, string> = {
  Escape: "escape",
  MetaLeft: "win",
  MetaRight: "win",
  ControlLeft: "lctrl",
  ControlRight: "rctrl",
  AltLeft: "lalt",
  AltRight: "ralt",
  ShiftLeft: "lshift",
  ShiftRight: "rshift",

  Digit1: "1",
  Digit2: "2",
  Digit3: "3",
  Digit4: "4",
  Digit5: "5",
  Digit6: "6",
  Digit7: "7",
  Digit8: "8",
  Digit9: "9",
  Digit0: "0",

  KeyA: "a",
  KeyB: "b",
  KeyC: "c",
  KeyD: "d",
  KeyE: "e",
  KeyF: "f",
  KeyG: "g",
  KeyH: "h",
  KeyI: "i",
  KeyJ: "j",
  KeyK: "k",
  KeyL: "l",
  KeyM: "m",
  KeyN: "n",
  KeyO: "o",
  KeyP: "p",
  KeyQ: "q",
  KeyR: "r",
  KeyS: "s",
  KeyT: "t",
  KeyU: "u",
  KeyV: "v",
  KeyW: "w",
  KeyX: "x",
  KeyY: "y",
  KeyZ: "z",

  F1: "f1",
  F2: "f2",
  F3: "f3",
  F4: "f4",
  F5: "f5",
  F6: "f6",
  F7: "f7",
  F8: "f8",
  F9: "f9",
  F10: "f10",
  F11: "f11",
  F12: "f12",

  Backquote: "backtick",
  Minus: "minus",
  Equal: "equals",
  Backspace: "backspace",
  Tab: "tab",
  BracketLeft: "lbracket",
  BracketRight: "rbracket",
  Backslash: "backslash",
  CapsLock: "capslock",
  Semicolon: "semicolon",
  Quote: "apostrophe",
  Enter: "enter",
  Comma: "comma",
  Period: "period",
  Slash: "slash",

  Delete: "delete",
  Home: "home",
  End: "end",
  PageUp: "pgup",
  PageDown: "pgdn",

  ArrowUp: "up",
  ArrowDown: "down",
  ArrowLeft: "left",
  ArrowRight: "right",

  NumLock: "numlock",
  NumpadDivide: "np_divide",
  NumpadMultiply: "np_multiply",
  NumpadSubtract: "np_subtract",
  NumpadAdd: "np_add",
  NumpadEnter: "np_enter",
  NumpadDecimal: "np_period",

  Numpad0: "np_0",
  Numpad1: "np_1",
  Numpad2: "np_2",
  Numpad3: "np_3",
  Numpad4: "np_4",
  Numpad5: "np_5",
  Numpad6: "np_6",
  Numpad7: "np_7",
  Numpad8: "np_8",
  Numpad9: "np_9",
};
